### ISSUE TITLE
Missing webworker support

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-bitswap#120]
- see: https://circleci.com/gh/ipfs/js-ipfs-bitswap/402

**Comment by diasdavid** [comment]
//cc @dryajov

**Comment by diasdavid** [comment]
It works now

**Comment by diasdavid** [comment]
Seems that it was a false positive. As we learned from https://github.com/ipfs/js-ipfs-bitswap/pull/142, WebWorker support for Bitswap tests (at least) is not there yet.

**Comment by dignifiedquire** [comment]
It works locally, just because travis is sad doesn't mean there is an actual issue

**Comment by diasdavid** [comment]
@VictorBjelkholm could you test it in your Linux env? It might be a Mac OS blessing (wouldn't be the first)

**Comment by diasdavid** [comment]
Ping @dryajov

**Comment by dryajov** [comment]
on it.
