### ISSUE TITLE
Create go-ipfs interop tests

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-bitswap#13]
- Use ipfsd-ctl to spawn go-nodes
- Spawn js-ipfs-bitswap instances
- Connect all of them 
- Exchange blocks

**Comment by diasdavid** [comment]
Might be hard to get just go-bitswap. Let's do these at js-ipfs level instead.

**Comment by diasdavid** [comment]
Let's bump this one into `js-ipfs` and use `ipfsd-ctl` to download go-ipfs and do interop tests.
