### ISSUE TITLE
Use modular async

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-bitswap#14]
- `parallel` and `each` => `run-parallel`
- `series` and `eachSeries` => `run-series`
- `parallelLimit` and `eachLimit` => `run-parallelLimit`
- `setImmediate` => `global.setImmediate` (shimmed through core-js already)
- `queue` => need more research

**Comment by diasdavid** [comment]
Note: [Use async 2.0 instead](https://github.com/ipfs/js-ipfs-bitswap/issues/14)

**Comment by diasdavid** [comment]
Anything blocking this one?

**Comment by dignifiedquire** [comment]
As the referenced commit says this is done in #25

**Comment by dignifiedquire** [comment]
Tracking in #25, closing here.
