### ISSUE TITLE
Notifications: More Generic events

### ISSUE THREAD

**Issue by ya7ya** [ipfs/js-ipfs-bitswap#151]
Hey @diasdavid and the IPFS team, I'm building something that requires getting a notification from `bitswap._notification` and noticed that it doesn't have more generic events, events are triggered with a string that includes the [`block.cid`](https://github.com/ipfs/js-ipfs-bitswap/blob/master/src/notifications.js#L36) usually. so creating a listener that listens to all `block:*` isn't that straightforward.

What if instead of using something like [`eventemitter2`](https://www.npmjs.com/package/eventemitter2) that adds wildcard and other functionalities , we can just trigger a more generic event like so
```javascript
// current implementation (notification.js)
hasBlock (block) {
    const str = `block:${block.cid.buffer.toString()}`
    this._log(str)
    this.emit(str, block)
 }

// proposed change
hasBlock (block) {
    const str = `block:${block.cid.buffer.toString()}`
    this._log(str)
    this.emit(str, block)
    // generic event
    this.emit('block', block)
}
```

What do you think?? Is this something you'd be interested in adding or not?

**Comment by diasdavid** [comment]
I'm not against it, my only humble request is that any kind of hooks and/or events to be well [documented and why](https://github.com/ipfs/js-ipfs-bitswap/pull/142#discussion_r135126146) otherwise it is prone to be changed or removed in the future.

**Comment by achingbrain** [comment]
I'm closing this because it's been almost three years with no movement here.  If you still need this functionality please open a PR.
