### ISSUE TITLE
"Multiplexer is destroyed"

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs-bitswap#167]
Sometimes we get this error in tests:

<img width="735" alt="continuous_integration_and_deployment" src="https://user-images.githubusercontent.com/47910/35850839-07293b72-0b1e-11e8-9c17-e020752eaf71.png">

**Comment by achingbrain** [comment]
The libp2p code behind this has been completely rewritten in the great async/await refactor so I'm not sure we'll ever get to the bottom of why this was happening.
