### ISSUE TITLE
It errors after latest release of Big.js

### ISSUE THREAD

**Issue by kenshyx** [ipfs/js-ipfs-bitswap#176]
```
Uncaught TypeError: Big is not a function
    at Stats.initialCounters.forEach (stat.js?ce0f:22)
```
This happens because Big.js uses now [default export](https://github.com/MikeMcl/big.js/blob/master/big.js#L925).

**Comment by diasdavid** [comment]
@alanshaw can you apply your fix here too? Or @vmx.

**Comment by vmx** [comment]
The big.js 5.1.2 release fixes this problem. Hence https://github.com/ipfs/js-ipfs-bitswap/commit/e451b3b47a914938da4085c2404a292873eae485 fixed this issue.
