### ISSUE TITLE
Non unique string CID keys

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs-bitswap#186]
As noted here https://github.com/libp2p/js-libp2p-floodsub/pull/59, two buffers of differing content do not necessarily produce a unique utf8 string when `toString` is called.

I noticed `toString` is being called on CID buffers, and that string is being used as a key for the CID that is wanted, if the buffer doesn't make a unique string then bitswap could potentially signal that we have a CID that we don't have!

https://github.com/ipfs/js-ipfs-bitswap/blob/399dc0ed09a36dae6c5df741eb59cc9026b2c473/src/notifications.js#L52

**Comment by vmx** [comment]
Should be fixed by https://github.com/ipfs/js-ipfs-bitswap/pull/191.
