### ISSUE TITLE
Use async/setImmediate instead of async/nextTick

### ISSUE THREAD

**Issue by satazor** [ipfs/js-ipfs-bitswap#196]
I've noticed that this module is using `async/nextTick` instead of `async/setImmediate`. Using `async/setImmediate` is preferred due to the way `async/nextTick` works in the browser:

> Calls callback on a later loop around the event loop. In Node.js this just calls process.nextTick. In the browser it will use setImmediate if available, otherwise setTimeout(callback, 0), which means other higher priority events may precede the execution of callback.

Because [timers are often throttled](https://developers.google.com/web/updates/2017/03/background_tabs) when a tab is not active to improve battery life, they only run at 1Hz (once every second). This has a drastic performance impact in those scenarios.

Will you accept a PR to change this?

Meanwhile, I'm aliasing `async/nextTick` to `async/setImmediate` in my webpack config.

**Comment by dirkmc** [comment]
Sure, please go ahead and make a PR. Thank you

**Comment by satazor** [comment]
Note that even if I change to `async/setImmediate` there's no guarantee that `setImmediate` will be available. In fact, in most browsers it doesn't. The thing is that webpack seems to automatically inject/polyfill `setImmediate` by default.

I will make a PR.

**Comment by achingbrain** [comment]
Please use `nextTick` over `setImmediate`.  The reason is because callbacks queued up by `process.nextTick` are executed at the end of the current tick, ones queued by `setImmediate` are executed at the start of the next tick (confusingly) which introduces a small amount of latency.  On hot codepaths this mounts up.

The NearForm team did a whole bunch of performance analysis of our code base at the beginning of the year and this was one of their findings - their recommendation was to avoid creating latency like this wherever possible.

**Comment by satazor** [comment]
@achingbrain I understand. For me this is actually a webpack problem because it's process.nextTick polyfill relies on setTimeout, which run once each 1sec if tab is not focused/active.

The sad reality is that most people using IPFS in the browser will experience the slowness as I was experiencing while webpack doesn't fix the underlying issue. I was willing to pinpoint the problem and it took me 3 hours, while most people won't and might just give up.

Feel free to close #197. I've opened an issue on Webpack: https://github.com/webpack/node-libs-browser/issues/92

I will keep the aliasing on my part to solve the issue.

**Comment by dirkmc** [comment]
Ok thanks @achingbrain for your input, I didn't know that. I will go ahead and close this issue and the PR as it sounds like the fix should be made in Webpack and @satazor has opened an issue with them.
