### ISSUE TITLE
I want to ask for some help.

### ISSUE THREAD

**Issue by AlphonseLeger** [ipfs/js-ipfs-bitswap#198]
In ipfs whitepaper, two formulas mentioned in the BitSwap Strategy section of BitSwap Protocol, one is about debt ratio r, that is: r = bytes_send / (bytes_recv + 1), i find the source code in ledger.js #43 , another formula is about the probability of sending to a debtor, that is: P(send | r) = 1 - 1 / (1 + exp(6-3r)), i haven't found the source code of another formula for a long time, anyone knows?

**Comment by dirkmc** [comment]
Hi @AlphonseLeger, currently the Bitswap Strategies are still an area of research, the formula you mentioned is not implemented in js-ipfs-bitswap

**Comment by AlphonseLeger** [comment]
thanks @dirkmc , so in the current IPFS client ,

**Comment by AlphonseLeger** [comment]
Thank you for answering this question @dirkmc , but, how does the debt ratio affect the nodes getting data from the network in the current IPFS client? Or the possibility that a node obtains data from the network is currently not affected by the debt ratio?

**Comment by dirkmc** [comment]
Hi @AlphonseLeger, currently it is not being used, in future it will be used for fairness algorithms.

**Comment by AlphonseLeger** [comment]
thanks very much @dirkmc

**Comment by dirkmc** [comment]
No problem, thank you for your interest 👍
