### ISSUE TITLE
Please lock multicodec dependency to 0.5.6

### ISSUE THREAD

**Issue by Maj0rT** [ipfs/js-ipfs-bitswap#208]
Today multicodec removed the file name-table.js which is used in js-ipfs-bitswap and released the new version 0.5.7.
Please lock multicodec dependency to 0.5.6, with 0.5.7 your source won't build.

Best regards,
Torsten

**Comment by dirkmc** [comment]
@Maj0rT sorry about that, this should be fixed by https://github.com/ipfs/js-ipfs-bitswap/pull/209. Please try the latest version (v0.26.2) and reopen if it doesn't work for you
