### ISSUE TITLE
Make CI green again

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-bitswap#34]
Due to CI being suuuper slow the browser tests time out while cleaning up databases. Resulting in a browser restart, making CI report red :( .Need to figure out how to fix this :(

**Comment by diasdavid** [comment]
I'm intrigued because we've stuffed way more data on IndexedDB in js-ipfs and the used pretty much the same in bitswap tests and it never failed this way. What made it more slower?

**Comment by dignifiedquire** [comment]
I don't know to be honest, the disconnect you are seeing in the logs I can not reproduce it locally. The reason why I think it is the db clean up is that is the last thing being logged before it disconnects. It might be something else that is slower on CI.

**Comment by dignifiedquire** [comment]
I would rather classify it as "CI has a bug" ;)

**Comment by diasdavid** [comment]
It worked before -> now it doesn't work and the PR that made it different was migration to pull-streams. We've to identify it because users will hit it too.

**Comment by dignifiedquire** [comment]
https://circleci.com/gh/ipfs/js-ipfs-bitswap/138 << there is not a single test failing here, not even the disconnect is happening 

I still think this is purely a failure in reporting/our tests as can be seen in the CircleiCI log above, so our users will not see this.

**Comment by dignifiedquire** [comment]
Sooo CircleCI is green after another retrigger: https://circleci.com/gh/ipfs/js-ipfs-bitswap/139
