### ISSUE TITLE
Retrieve blocks from a specific peer / Improved peer metrics

### ISSUE THREAD

**Issue by vaultec81** [ipfs/js-ipfs-bitswap#346]
Greetings! I am looking for a way to query a single bitswap peer for a chunk of data without potentially querying other peers. The motivation is for getting very accurate metrics on how performant a peer can supply a piece of data (latency, overall throughput, etc). I understand there is [Peer accessor](https://github.com/ipfs/js-ipfs-bitswap#peer-accessor), but it only shows *very* brief details about another peer, nothing like throughput or what blocks the peer has provided to me. 

The core feature set of this are:
1. Average latency a peer has provided me blocks at
2. Average throughput a peer has provided me blocks at. How many blocks (256kb size) can be pulled per second. This would require multiple blocks to be queries in rapid succession, but this is the general idea. 
3. A list of blocks (CIDs) a peer has provided me (unique and duplicated blocks)

All of the above would need a temporary store (in memory) to track averages overtime and CID list of blocks. 

Secondary features:
1. Ability to focus on a single node, disregard (do not ask) any other nodes for data except for the one being focused on.
2. Individual metrics per block, think of 10ms to retrieve block X from when provided wantlist to peer. This also would include the peerId that provided the block. Firing a javascript event is one way to go about doing this. 
3. Ability to "skip" accessing localstorage for blocks

For number 3 above: Ideally, this would involve some decoupling of the underlying data store from bitswap or at the very least add an option to `get` and `getMany` to skip accessing datastore. My understanding is js-ipfs-bitswap is heavily integrated with a local datastore, but this can be addressed at a later date.

For some perspective many bittorrent clients provide a significant amount of information about what peers are sending data to the node and at what throughput. It would be great to have similar functionality in bitswap and ipfs. I understand this functionality can be built into bitswap without official support (as it's implementation specific and does not break the protocol as a whole from my understanding), but I do want to see official support for such a thing. Outside of *just* collecting more metrics, this could be useful for prioritizing which peers to send blocks to based upon lowest latency and highest throughput in the future.

Thank you for taking the time to read through all this. I'd appreciate further comments, discussion and feedback. If there is anything I am missing here or misunderstood, correction is always welcome.

**Comment by achingbrain** [comment]
You could do this for research purposes by configuring an IPFS node with a [custom libp2p instance](https://github.com/ipfs/js-ipfs/blob/master/docs/MODULE.md#optionslibp2p) that only bootstraps to the node you wish to measure and has all other peer discovery disabled.

For the more detailed stats a PR to this module would be required.  It's a neat idea though, network performance transparency would be very helpful, particularly it would be integrated into the [webui](https://github.com/ipfs/ipfs-webui).

**Comment by lidel** [comment]
@vaultec81 do you mind explaining your use case / provide more high level context? I feel this wishlist could be prioritized/triaged better if we got the big picture of sorts.

**Comment by vaultec81** [comment]
> You could do this for research purposes by configuring an IPFS node with a [custom libp2p instance](https://github.com/ipfs/js-ipfs/blob/master/docs/MODULE.md#optionslibp2p) that only bootstraps to the node you wish to measure and has all other peer discovery disabled.

This would work for throughput and querying a specific peer, but not latency. More of a hack then a proper solution for this and it wouldn't allow me easily to query multiple peers without restarting the entire ipfs bundle each time.

**Comment by BigLep** [comment]
@vaultec81 : this particular ask isn't a high priority for the maintainers.  Are you considering doing the implementation?  If so, could you please put together a design proposal and a project plan / task list.  We could help review that to make sure you're pointing in a good direction.  Thanks!

**Comment by vaultec81** [comment]
@BigLep 
> this particular ask isn't a high priority for the maintainers. Are you considering doing the implementation? If so, could you please put together a design proposal and a project plan / task list.

Is there a link for how to do this / examples? Where would this project plan go exactly?

**Comment by lidel** [comment]
@vaultec81 please just write down how the API you would like to add looks like – does not need to be in-depth, an example of usage in your app would be the best. 

This gives us basis for any tweaks/suggestions  before you invest time in implementing it.

**Comment by lidel** [comment]
Closing as stale, feel free to reopen when you have time/will to write the design proposal.
