### ISSUE TITLE
Reduce the number of messages sent by coalescing the ones queue

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-bitswap#85]
As noted in https://github.com/ipfs/js-ipfs-bitswap/pull/76#issue-194743947

> I don't see any code to coalesce messages in the messages queues, which means the more peers we have, the more buffering it will happen, to the point where the message to reset the wantlist might be added even before the previous having been sent and nothing is clearing the message queue.

This will improve performance and reduce the memory usage by a lot

**Comment by dignifiedquire** [comment]
Already done in the performance optimisations pr
