### ISSUE TITLE
Why is there a refcounter for PeerHandler in the WantManager?

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-bitswap#87]
I've asked this in this issue https://github.com/ipfs/js-ipfs-bitswap/pull/76

@dignifiedquire ?

**Comment by diasdavid** [comment]
Ping :)

**Comment by diasdavid** [comment]
@dignifiedquire please brain dump 🙏🏽

**Comment by dignifiedquire** [comment]
To handle this: https://github.com/ipfs/js-ipfs-bitswap/blob/master/src/want-manager/index.js#L77-L82

If I remember correctly I ported this from the implementation in go. I am not a 100% sure this is still needed in the current version of the implementation, but if you remove it, it should be looked at very carefully that it doesn't break anything.
