### ISSUE TITLE
Reconsider the MessageQueue per peer approach

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-bitswap#88]
As asked here: https://github.com/ipfs/js-ipfs-bitswap/pull/76

> Is a MessageQueue per peer the best approach? Why not piggyback on want list updates and just check what the peer wants and attach the blocks necessary?

It might be tad expensive to have a message queue for each peer, especially with a lot of Peer Churn

**Comment by dignifiedquire** [comment]
After the perf PR it is not a queue anymore, simply a buffer to combine message sending. I haven't found a good name for it yet though.

**Comment by diasdavid** [comment]
Interesting, need to read the new approach, didn't realise you applied it after I commented it out on the CID PR :)
