### ISSUE TITLE
Port tests from go-bitswap

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-bitswap#9]
We want all these tests ported: https://github.com/ipfs/go-ipfs/blob/master/exchange/bitswap/bitswap_test.go

Depends on #8

**Comment by diasdavid** [comment]
We have a script to spawn a network of bitswap nodes. Anything else missing to make this happen?

**Comment by dignifiedquire** [comment]
There are some more unit tests inside that I wanted to be in here go-bitswap

**Comment by diasdavid** [comment]
Sounds great to me :) tests tests tests :D

**Comment by dignifiedquire** [comment]
Moving this to milestone 5 when we have routing enabled, makes more sense to do the testing then.

**Comment by pgte** [comment]
From my read, go tests create a virtual network with a fixed delay.
Currently, js-ipfs-bitswap tests use the TCP transport.
Should these new tests use a virtual network with similar characteristics?
If so, is there anything in place?

**Comment by diasdavid** [comment]
Work happening here https://github.com/ipfs/js-ipfs-bitswap/pull/159
