### ISSUE TITLE
Continue to refactor until we get something really simple

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-bitswap#91]
I feel that it requires a huge cognitive investment to dial into bitswap, before https://github.com/ipfs/js-ipfs-bitswap/pull/76 there was not documentation making it hard to understand what is what. Also, there are a lot of design decisions that simply aren't clear from reading the code and once you start describing them, you realise that it can be so much more improved (as also noted in https://github.com/ipfs/js-ipfs-bitswap/pull/76).

I would like for bitswap to reach a state where it is just obvious to understand how it works, how to improve it and how to use different bitswap strategies. I know there is some interest in the community to experiment with variations of bitswap.

I know this is a very abstract request, but there are some action items that we can start with:

- [ ] Make code more modular (reduce size of files, right now it requires a lot of scrolling)
- [ ] Improve documentation even further (graphs, more graphs :))
- [ ] Explain design rationale and reference material for contributors to get a good grasp of 'why it is this way'
- [ ] Have a way to visualise (like this http://mg8.org/processing/bt.html but better)

**Comment by diasdavid** [comment]
A step forward towards this direction #142
