### ISSUE TITLE
Limit message size to 4MB

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-bitswap#92]
Need to

- check limit on incoming messages.
- split outgoing messages into multiple if they are large.

**Comment by diasdavid** [comment]
Seems the pattern that we are looking here is a [`cargo`](http://caolan.github.io/async/docs.html#cargo) instead of using the `queue`. Both available in async

**Comment by diasdavid** [comment]
@dignifiedquire you limited to 2MB, right?

**Comment by dignifiedquire** [comment]
Yes outgoing messages are now limited, but not incoming messages

**Comment by diasdavid** [comment]
sounds good, incoming should not be an issue for now.
